org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

enabled_platforms=forge,fabric,neoforge

archives_base_name=nbtedit

mod_id=nbtedit
mod_name=NBTEdit
mod_full_name=In-game NBTEdit Reborn
mod_version=5.2.12

minecraft_version=1.21.5

parchment_minecraft_version=1.21.5
parchment_version=2025.06.15

fabric_loader_version=0.17.2
fabric_api_version=0.128.2+1.21.5
fabric_permission_api_version=0.3.3
mod_menu_version=14.0.0-rc.2

forge_version=55.1.2
neoforge_version=21.5.95

forge_loader_version_range=[55,)
forge_version_range=[55,)
forge_minecraft_version_range=[1.21.5,)

neoforge_loader_version_range=[4,)
neoforge_version_range=[21.5,)
neoforge_minecraft_version_range=[1.21.5,)

fabric_loader_version_range=>=0.16
fabric_api_version_range=*
fabric_permission_api_version_range=>=0.3.3
fabric_minecraft_version_range=>=1.21.5

releasing_minecraft_versions=1.21.5
