org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

enabled_platforms=forge,fabric,neoforge

archives_base_name=nbtedit

mod_id=nbtedit
mod_name=NBTEdit
mod_full_name=In-game NBTEdit Reborn
mod_version=5.2.15

minecraft_version=1.21.10

parchment_minecraft_version=1.21.10
parchment_version=2025.10.12

fabric_loader_version=0.17.2
fabric_api_version=0.135.0+1.21.10
fabric_permission_api_version=0.5.0
mod_menu_version=16.0.0-rc.1

forge_version=60.0.0
neoforge_version=21.10.5-beta

forge_loader_version_range=[59,)
forge_version_range=[59,)
forge_minecraft_version_range=[1.21.9,)

neoforge_loader_version_range=[4,)
neoforge_version_range=[21.9,)
neoforge_minecraft_version_range=[1.21.9,)

fabric_loader_version_range=>=0.16
fabric_api_version_range=*
fabric_permission_api_version_range=>=0.5.0
fabric_minecraft_version_range=>=1.21.9
