architectury {
    forge()
}

loom {
    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
    }

    runs {
        client {
            client()

            runDir 'run/client'

            // To support the Enhanced Class Redefinition in JBR.
            vmArg '-XX:+IgnoreUnrecognizedVMOptions'
            vmArg '-XX:+AllowEnhancedClassRedefinition'

            // https://openjdk.org/jeps/400
            property 'file.encoding', 'COMPAT'
        }

        server {
            server()
            runDir 'run/server'
            vmArg '-XX:+IgnoreUnrecognizedVMOptions'
            vmArg '-XX:+AllowEnhancedClassRedefinition'
            property 'file.encoding', 'COMPAT'
        }

        configureEach {
            property 'eventbus.api.strictRuntimeChecks', 'true'
        }
    }
}

configurations {
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.12'

    common(project(path: ':nbtedit-common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':nbtedit-common', configuration: 'transformProductionForge')
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

unifiedPublishing {
    project {
        displayName = "NBTEdit Forge ${project.minecraft_version}-${project.mod_version}"
        version = publishVersion
        gameVersions = [project.minecraft_version, '1.21.9']
        gameLoaders = ['forge']
        releaseType = 'release'

        mainPublication tasks.remapJar

        curseforge {
            token = Objects.requireNonNullElse(System.getenv('CURSEFORGE_TOKEN'), "")
            id = '678133'
        }

        modrinth {
            token = Objects.requireNonNullElse(System.getenv('MODRINTH_TOKEN'), "")
            id = 'Vr2eDeCw'
        }
    }
}
