architectury {
    forge()
}

loom {
    forge {
        convertAccessWideners = true
        extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
    }

    runs {
        configureEach {
            property 'eventbus.api.strictRuntimeChecks', 'true'
        }
    }
}

configurations {
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'

    common(project(path: ':nbtedit-common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':nbtedit-common', configuration: 'transformProductionForge')
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

unifiedPublishing {
    project {
        displayName = "NBTEdit Forge ${project.minecraft_version}-${project.mod_version}"
        version = publishVersion
        gameVersions = [project.minecraft_version]
        gameLoaders = ['forge']
        releaseType = 'release'

        mainPublication tasks.remapJar

        curseforge {
            token = Objects.requireNonNullElse(System.getenv('CURSEFORGE_TOKEN'), "")
            id = '678133'
        }

        modrinth {
            token = Objects.requireNonNullElse(System.getenv('MODRINTH_TOKEN'), "")
            id = 'Vr2eDeCw'
        }
    }
}
